export const keyToLabel = {
  Pregnancies: "Number of Pregnancies",
  Glucose: "Glucose Level (mg/dL)",
  BloodPressure: "Blood Pressure (mm Hg)",
  SkinThickness: "Skin Thickness (mm)",
  Insulin: "Insulin Level (mu U/ml)",
  BMI: "Body Mass Index (kg/m²)",
  DiabetesPedigreeFunction: "Diabetes Pedigree Function",
  Age: "Age (years)",
  Outcome: "Outcome (0 = No Diabetes, 1 = Diabetes)",
};

export const colors = {
  Pregnancies: "#8884d8",
  Glucose: "#82ca9d",
  BloodPressure: "#ffc658",
  SkinThickness: "#ff7300",
  Insulin: "#a4de6c",
  BMI: "#d0ed57",
  DiabetesPedigreeFunction: "#ff0000",
  Age: "#00ffff",
};

export const diabetesData = [
  {
    id: 1,
    Pregnancies: 6,
    Glucose: 148,
    BloodPressure: 72,
    SkinThickness: 35,
    Insulin: 0,
    BMI: 33.6,
    DiabetesPedigreeFunction: 0.627,
    Age: 50,
    Outcome: 1,
  },
  {
    id: 2,
    Pregnancies: 1,
    Glucose: 85,
    BloodPressure: 66,
    SkinThickness: 29,
    Insulin: 0,
    BMI: 26.6,
    DiabetesPedigreeFunction: 0.351,
    Age: 31,
    Outcome: 0,
  },
  {
    id: 3,
    Pregnancies: 8,
    Glucose: 183,
    BloodPressure: 64,
    SkinThickness: 0,
    Insulin: 0,
    BMI: 23.3,
    DiabetesPedigreeFunction: 0.672,
    Age: 32,
    Outcome: 1,
  },
  {
    id: 4,
    Pregnancies: 1,
    Glucose: 89,
    BloodPressure: 66,
    SkinThickness: 23,
    Insulin: 94,
    BMI: 28.1,
    DiabetesPedigreeFunction: 0.167,
    Age: 21,
    Outcome: 0,
  },
  {
    id: 5,
    Pregnancies: 0,
    Glucose: 137,
    BloodPressure: 40,
    SkinThickness: 35,
    Insulin: 168,
    BMI: 43.1,
    DiabetesPedigreeFunction: 2.288,
    Age: 33,
    Outcome: 1,
  },
  {
    id: 6,
    Pregnancies: 5,
    Glucose: 116,
    BloodPressure: 74,
    SkinThickness: 0,
    Insulin: 0,
    BMI: 25.6,
    DiabetesPedigreeFunction: 0.201,
    Age: 30,
    Outcome: 0,
  },
  {
    id: 7,
    Pregnancies: 3,
    Glucose: 78,
    BloodPressure: 50,
    SkinThickness: 32,
    Insulin: 88,
    BMI: 31,
    DiabetesPedigreeFunction: 0.248,
    Age: 26,
    Outcome: 1,
  },
  {
    id: 8,
    Pregnancies: 10,
    Glucose: 115,
    BloodPressure: 0,
    SkinThickness: 0,
    Insulin: 0,
    BMI: 35.3,
    DiabetesPedigreeFunction: 0.134,
    Age: 29,
    Outcome: 0,
  },
  {
    id: 9,
    Pregnancies: 2,
    Glucose: 197,
    BloodPressure: 70,
    SkinThickness: 45,
    Insulin: 543,
    BMI: 30.5,
    DiabetesPedigreeFunction: 0.158,
    Age: 53,
    Outcome: 1,
  },
  {
    id: 10,
    Pregnancies: 8,
    Glucose: 125,
    BloodPressure: 96,
    SkinThickness: 0,
    Insulin: 0,
    BMI: 0,
    DiabetesPedigreeFunction: 0.232,
    Age: 54,
    Outcome: 1,
  },
  // Additional 40+ entries would follow this pattern...
  {
    id: 51,
    Pregnancies: 1,
    Glucose: 93,
    BloodPressure: 60,
    SkinThickness: 25,
    Insulin: 92,
    BMI: 28.7,
    DiabetesPedigreeFunction: 0.532,
    Age: 22,
    Outcome: 0,
  },
  {
    id: 52,
    Pregnancies: 0,
    Glucose: 129,
    BloodPressure: 80,
    SkinThickness: 0,
    Insulin: 0,
    BMI: 31.2,
    DiabetesPedigreeFunction: 0.703,
    Age: 29,
    Outcome: 0,
  },
  // Continue adding entries until all CSV rows are converted
];
